name: MyWelcomeApp
main: Darren2005\MyWelcomeApp\Main
version: 1.0.1
api: 5.0.0
author: Darren Edwards
description: Welcome plugin with many cool features!

commands:
  hello:
    description: Say hello!
    usage: /hello
    permission: mywelcomeapp.hello

  sethome:
    description: Set your home location
    usage: /sethome
    permission: mywelcomeapp.sethome

  home:
    description: Teleport to your home
    usage: /home
    permission: mywelcomeapp.home

permissions:
  mywelcomeapp.hello:
    description: Allows the player to use /hello
    default: true

  mywelcomeapp.sethome:
    description: Allows players to set their home location
    default: true

  mywelcomeapp.home:
    description: Allows players to teleport to their home
    default: true

  mywelcomeapp.admin:
    description: Allows access to admin settings
    default: op
