# MyWelcomeApp Configuration

# Customize the welcome message players see when they join the server
welcome-message: "Welcome to the server, {player}! Have a great time!"

# Enable or disable the welcome message feature
enable-welcome: true

# Enable or disable the /hello command
enable-hello-command: true
# Enable or disable join titles and action bar messages
enable-title-message: true
enable-actionbar-message: true
# Enable or disable first-time join rewards
enable-join-reward: true
reward-item: "golden_apple"
reward-amount: 3
custom-join-message: "{player} has joined the adventure!"
custom-leave-message: "{player} has left the world!"
# Enable or disable welcome fireworks
enable-fireworks: true
welcome-messages:
  - "Welcome {player}, enjoy your stay!"
  - "Hello {player}, have fun on our server!"
  - "Hey {player}, let’s start an adventure!"
  - "Great to see you, {player}!"
